name: Deploy Lambda via SAM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build Lambda function
        run: sam build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda function
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name news-aggregator-lambda \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}
